### ISSUE TITLE
Disable small pulse animation when max value reached

### ISSUE THREAD

**Issue by yarodevuci** [Ramiz69/Slider#1]
Hi, thanks for cool slider.
How can I remove animation on the slider when I slide to max value?
There is a slight magnetic animation movement to view bound. 

**Also, where in the code best to add tactical vibration feedback?**

@Ramiz69

**Comment by Ramiz69** [comment]
Hi, i added haptic generator and HapticConfiguration class, also i fixed track layer when the slider reach max value. I hope i helped you
