### ISSUE TITLE
iPad Bug

### ISSUE THREAD

**Issue by yarodevuci** [Ramiz69/Slider#2]
Weird bug I noticed for iPad devices
If I run the app on release mode Slider is not fully visible, If I run the app in Debug mode everything is ok. iOS15
@Ramiz69 

Release
![IMG_18C91F0225BB-1](https://user-images.githubusercontent.com/13408859/151065073-b4073fb4-90f8-44c9-a544-fb00eb8043ce.jpeg)

Debug
<img width="760" alt="Screen Shot 2022-01-25 at 1 46 53 PM" src="https://user-images.githubusercontent.com/13408859/151065158-9b06a8c3-f8f8-4435-8a0a-2a24ce2a0498.png">

**Slider** is configured via StoryBoard, with Top, Leading and Trailing Constraints. If build in iPhone preview on Storyboard selected bug is present. If I change iPad preview on Storyboard and build bug is not present. 

Bug is reproducible in your Demo App via Storyboard 
<img width="763" alt="Screen Shot 2022-01-25 at 2 34 51 PM" src="https://user-images.githubusercontent.com/13408859/151071083-7a06b4c5-58a7-4dca-8dcb-ffe819df5450.png">

**Comment by Ramiz69** [comment]
Fixed
