### ISSUE TITLE
Can vertical mode be added

### ISSUE THREAD

**Issue by Wuou** [Ramiz69/Slider#4]
Can vertical mode be added

**Comment by Ramiz69** [comment]
Hi, great idea. I'll do this soon. Thanks!

**Comment by Wuou** [comment]
> Hi, great idea. I'll do this soon. Thanks!嗨，好主意。我马上就去。谢谢你，谢谢

Oh, thank you very much

**Comment by Ramiz69** [comment]
Done

**Comment by Wuou** [comment]
> Done
Nice!
